### ISSUE TITLE
Poimenovanje datotek

### ISSUE THREAD

**Issue by jaanos** [Tomaz4/veterinarska-ambulanta#1]
Trenutno imata na repozitoriju datoteki `veterinarska_ambulanta (1).sqlite` in `veterinarska_ambulanta (1)(1).sqlite`. Ideja git-a je, da se hranijo vse vmesne različice, tako da ni potrebe, da bi imeli na repozitoriju hkrati več različic iste datoteke.

Če imata dober razlog za to, da sta na repozitoriju dve bazi, pa seveda poskrbita za ustrezno poimenovanje datotek - da bo takoj jasno, za kaj se gre pri vsaki.

Sicer pa svetujem, da raje kot da nalagata datoteke preko GitHuba, za sinhronizacijo uporabita vmesnik za git (dobita ga npr. na https://git-scm.com/downloads, če ga še nimata). Tako bosta lahko enostavno delala na svoji kopiji repozitorija, z vmesnikom pa lahko potem pregledata, katere datoteke so se spremenile, in jih tako vključita v commit.

**Comment by Tomaz4** [comment]
Hvala za nasvet, bova delala sedaj naprej preko vmesnika. 
Prav tako imava sedaj samo eno ".sqlite" datoteko, ki je ustrezno preimenovana.

**Comment by jaanos** [comment]
V redu, bi pa vseeno svetoval, da informacije, da je to npr. `dopolnjenaBaza`, nimate v imenu datoteke (tega načeloma ne želite spreminjati), pač pa v sporočilu ob commitu (na GitHubu se bo ob datoteki izpisalo sporočilo zadnjega commita, ki je spreminjal datoteko; lahko pa pogledata tudi zgodovino posamezne datoteke, da vesta, kako se je spreminjala).

Ko rešita problem, zadevo (*issue*) zaprita - lahko z odgovorom in klikom na **Close and comment**, lahko pa tudi v sporočilo ob commitu, ki razreši zadevo, napišeta npr. `close #1` (kjer je #1 številka zadeve), pa se bo zadeva sama zaprla (in bo možno videti, kateri commit jo je zaprl).

**Comment by ghost** [comment]
Bova upoštevala.
