### ISSUE TITLE
Thumbs.db

### ISSUE THREAD

**Issue by jaanos** [Tomaz4/veterinarska-ambulanta#2]
Na repozitorij se vama je izmuznila datoteka `Thumbs.db`, ki pa tja ne sodi, saj gre za datoteko z ikonami, ki v Windowsih predstavljajo mapo. Svetujem, da jo pobrišeta z repozitorija, v vrhnji mapi pa ustavrita datoteko `.gitignore`, ki določa, katere datoteke naj se ne dodajajo v repozitorij. Vsebina je lahko taka:
```
*~
*.pyc
__pycache__
Thumbs.db
.DS_Store
```
Skratka, vsaka vrstica predstavlja vzorec za imena datotek, ki naj se ne dodajajo v repozitorij. Tukaj so poleg `Thumbs.db` še mapa `__pycache__` in datoteke s končnico `.pyc`, ki ustrezajo prevedenim Pythonovim datotekam, mapa `.DS_Store`, ki ima v MacOS podobno vlogo kot `Thumbs.db`, ter datoteke z zadnjim znakom `~`, ki jih nekateri programi ustvarijo kot začasne datoteke. Po potrebi lahko dodasta še kak vnos.

**Comment by ghost** [comment]
Dodano.
