### ISSUE TITLE
Uporaba rebase

### ISSUE THREAD

**Issue by matijapretnar** [Tomaz4/veterinarska-ambulanta#3]
Kot gledam, ima vsak vajin template malenkost drugačno HTML strukturo. Da bodo stvari videti konsistentne in s tem lepe, je bolje narediti osnovo in potem uporabiti `rebase`. Za primer si oglejta TilenNoc/Knjiznica#3.

**Comment by ghost** [comment]
Bova uporabila rebase.

**Comment by jaanos** [comment]
Mimogrede, spodobi se, da najprej uredita zadevo in jo šele potem zapreta.
